# Generated by Django 4.1.5 on 2023-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
